# Generated by Django 5.1.3 on 2024-12-03 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_order_address_order_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Customer',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='Product',
            new_name='product',
        ),
    ]
